### PR TITLE
#163 - Rename autogenerated "get" commands

### PR DESCRIPTION
**Pull request by garciparedes**

### CODE REVIEW

**Review by albamig — CHANGES_REQUESTED** [review]
Great @garciparedes! The new name looks somewhat misleading to me, though. What do you think about renaming it to `_MinosGetOrder`? In my opinion, this way it's clearer that those endpoints are generated by the framework, so that in case anybody comes to see them they'll know immediatelly.

**Comment by garciparedes** [comment]
> Great @garciparedes! The new name looks somewhat misleading to me, though. What do you think about renaming it to `_MinosGetOrder`? In my opinion, this way it's clearer that those endpoints are generated by the framework, so that in case anybody comes to see them they'll know immediatelly.

Hi @albamig! That name was one of the options I were thinking about, but finally I decided not to add `Minos`-like words to the topic names. The solution I decided to follow is simply adding an underscore prefix for internal topics (`kafka` uses a similar approach for consumer offsets).

To be more consistent and completely avoid topic naming collisions, I also propose to restrict the topic names defined at the application-level, raising an exception if any of them start with an underscore.

Do you agree with this approach?

**Comment by albamig** [comment]
> > Great @garciparedes! The new name looks somewhat misleading to me, though. What do you think about renaming it to `_MinosGetOrder`? In my opinion, this way it's clearer that those endpoints are generated by the framework, so that in case anybody comes to see them they'll know immediatelly.
> 
> Hi @albamig! That name was one of the options I were thinking about, but finally I decided not to add `Minos`-like words to the topic names. The solution I decided to follow is simply adding an underscore prefix for internal topics (`kafka` uses a similar approach for consumer offsets).
> 
> To be more consistent and completely avoid topic naming collisions, I also propose to restrict the topic names defined at the application-level, raising an exception if any of them start with an underscore.
> 
> Do you agree with this approach?

It's okay then!

And what about the `xxxSnapshot(s)` suffix? That's an implementation detail that shouldn't be important in an endpoint's name. What do you think?

**Comment by garciparedes** [comment]
> And what about the `xxxSnapshot(s)` suffix? That's an implementation detail that shouldn't be important in an endpoint's name. What do you think?

Hi @albamig, the reason is to avoid future collisions if we're future commands like `GetProductEvents` and so on.

**Comment by albamig** [comment]
> > And what about the `xxxSnapshot(s)` suffix? That's an implementation detail that shouldn't be important in an endpoint's name. What do you think?
> 
> Hi @albamig, the reason is to avoid future collisions if we're future commands like `GetProductEvents` and so on.

Ok then! Good job!

**Review by albamig — APPROVED** [review]

**Pull request merged**
